export const SET_FOOD_SELECTED = 'SET_FOOD_SELECTED';
export const SET_SHOPPING_CART = 'SET_SHOPPING_CART';
export const SET_FILTER_KIND_SELECTED = 'SET_FILTER_KIND_SELECTED';
export const SET_FILTER_TEXT_SEARCH = 'SET_FILTER_TEXT_SEARCH';
export const SET_KINDS = 'SET_KINDS';